### ISSUE TITLE
Fixing the serverside lua access exploit

### ISSUE THREAD

**Issue by JesusCrazy42** [wiremod/wire-cpu#5]
The ZCPU chips are an important part of wiremod and i think they should return to base wiremod

Those are some reasons why i think the ZCPU chips should come back to base wiremod:
1. The CPU, GPU and SPU chips are very useful when it comes to creating virtual computers and consoles on garry's mod
2. The GPU has 3D capable features while the Expression 2's EGP can't do 3D graphics that well
3. The ZCPU has a powerful instruction set capable of advanced stuff like page management, interrupt handling and matrix math
4. The ZCPU's Virtual Machine is really helpful when it comes to executing code that is stored on a DHDD
5. The ZCPU's Virtual Machine is really fast, capable of executing around 1400000 instructions per tick without lagging the server
6. If the ZCPU doesn't come with the base wiremod, newcomers won't know about the powerful features that the ZCPU comes with
7. The serverside lua access exploit should have an easy solution

**Comment by thegrb93** [comment]
If 7. gets addressed then it should be possible to bring back

**Comment by JesusCrazy42** [comment]
Do you know what are the causes of the exploit?

**Comment by Vurv78** [comment]
> The serverside lua access exploit should have an easy solution

Maybe. But the fact it is transpiled and the original dev isn't available (and has largely forgotten about the project after a decade) always leaves room for holes.

Also, the serverside lua exploit wasn't the only reason why it was removed from the base mod. It hasn't been worked on for a decade so the bugs and code quality are completely stagnant.

Removing it has opened up a slot for a new, actually maintained chip. So for the rest of the points, there's work on a new chip. We can see if that goes anywhere and come back to this.

> If the ZCPU doesn't come with the base wiremod, newcomers won't know about the powerful features that the ZCPU comes with

To be fair I doubt there's really any newcomers to CPU or GPU anymore, which is why removal was on the table anyway.

> The ZCPU's Virtual Machine is really fast, capable of executing around 1400000 instructions per tick without lagging the server

If you want speed, you use starfall or E2 on my new compiler https://github.com/wiremod/wire/pull/2555.
CPU's speed shouldn't even be a plus, theoretically being transpiled it should wipe the floor with E2 and Starfall, yet it doesn't

# 

Either way I don't want it coming back to the base repository, at least I'd prefer it being fetched from here and packaged. Having it in a separate repo separates the bugs that would practically never be addressed otherwise.

Would be really easy to bundle it for the workshop but for the repo, pretty tricky...

**Comment by Vurv78** [comment]
> Do you know what are the causes of the exploit?

Transpiling code would concatenate numbers for certain instructions, however malicious users could try and stick a string where a number should be since lua allows concatenating both numbers and strings.

Would need to sanitize all of the transpiling code (saw 2000 lines and didn't want to bother) to leave no holes open for exploiting. Yes you can say you sanitize the wire inputs, but we did that twice and apparently people were still exploiting it.

**Comment by JesusCrazy42** [comment]
Should it be a good idea to add the CPU chips to the workshop as a separate addon?

**Comment by thegrb93** [comment]
Not until 7. is addressed.

**Comment by JesusCrazy42** [comment]
well, then i guess it's better to leave the ZCPU chips archived on this repo

**Comment by JesusCrazy42** [comment]
should i close this issue or leave it open?

**Comment by thegrb93** [comment]
Probably fine to leave open

**Comment by DerelictDrone** [comment]
ZCPU is presently back on the workshop, as the original RCE is fixed, however this issue shall remain open for a while as there's no guarantee a new RCE won't be found.

**Comment by DerelictDrone** [comment]
With #48 merged, the chances of new RCE's cropping up that cause major issues should be fairly low, so this can be closed I feel.
